apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: poke-pipeline-insights
  labels:
    app: poke-pipeline
    phase: insights
spec:
  schedule: "*/30 * * * *"              # every 30 minutes
  timezone: "UTC"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 300
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  workflowSpec:
    workflowTemplateRef:
      name: poke-pipeline
    arguments:
      parameters:
        - name: phase
          value: insights
